### ISSUE TITLE
How to invoke print preview by js code

### ISSUE THREAD

**Issue by rj-hwang** [jhonatasrm/print-preview#11]
Use `window.print()` do not show print preview. Can I invoke print preview by use this extension on js code?

**Comment by jhonatasrm** [comment]
Hello! 
> Can I invoke print preview by use this extension on js code?

For this Add-on I'm using the <a href="https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions">WebExtensions API</a>... So I'm afraid you're not able to do that because this is an Add-on and the user of your Website will need the Add-on in their browser (assuming you are able to create a code invoking the Add-on). Also even if you use the code of the Add-on on your js code, you will need the permission and the WebExtensions API.

There are some jQuery plugins that can help you call print preview mode on your Website in an easy way, you can see some of them, <a href="https://www.learningjquery.com/2017/10/10-awesome-jquery-print-page-plugins">here</a>.



P.S. You always can recommend the Add-on to the users of your page. :)
